### ISSUE TITLE
ccgbt_init_extd 是不是有寫錯?

### ISSUE THREAD

**Issue by chrisdartw** [kevin-dong-nai-jia/OpenGC3#2]
_itarr_init 會使用三參數的ccgbt_iter_init 但是實際上 ccgbt_iter_init 只有兩參數

`#define ccgbt_init_extd(_ccgbt, _start, _ratio, _thrsh)                        \
                                                                               \
STATEMENT_                                                                     \
(                                                                              \
    (_ccgbt) = NULL;                                                           \
                                                                               \
    _ccgbt_init_extd((_ccgbt), (_start), (_ratio), (_thrsh), 1);               \
                                                                               \
    _itarr_init((_ccgbt), ccgbt);                                              \
    _ccgbt_iter_init((_ccgbt)->_iter, (_ccgbt), 1);                            \
)
`

**Comment by kevin-dong-nai-jia** [comment]
目前 `ccgbt` 容器的開發由 @andylinpersonal  負責，但是目前進度延宕並且疏於測試。部分 `ccgbt` 使用的 macro 並沒有與主要的容器 `ccxll`, `ccdll`, `ccsll` 共用的接口一致，可能會造成編譯錯誤。

此外，本專案為研發性質的研究（科技部計畫編號：`106-2813-C-009-027-E`），探討函式呼叫 overhead 以及特殊的排序演算法，因此並不建議用於 production code，謝謝。
